import io.flutter.embedding.android.FlutterActivity;
/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
public class MainActivity extends FlutterActivity{}
